version: "3.2"
services:
  hazelcast-genny:
    image: gennyproject/swarmtest:latest
    hostname: hazelcast-genny 
#    volumes:
#      - ./realm:/opt/realm
#    env_file:
#      - ${ENV_FILE}
    environment:
      - VIRTUAL_HOST=vertx.genny.life
      - VIRTUAL_PROTO=https
      - VIRTUAL_PORT=8081
      - LETSENCRYPT_HOST=vertx.genny.life
      - LETSENCRYPT_EMAIL=acrow@outcome.life
      - DOCKER_HOST=http://${HOST_IP}:2376
    command: java -DdockerNetworkNames=genny-network -DdockerServiceNames=swarmtest_hazelcast-genny -DhazelcastPeerPort=5701 -jar /test.jar 
    networks:
      - genny-network 
    deploy:
      replicas:  2 
      #endpoint_mode: vip
      update_config:
         parallelism: 2 
         delay: 10s
      labels:
        - life.genny.name=swarmtest
#      placement:
#        constraints:
#          - "node.hostname == gerard"
#          - "node.role == manager"
#          - "node.role == worker"



networks:
#  hazelcast-genny:
  genny-network:
    external: true
